services:
  web:
    container_name: alarcia-dev
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - gh_token
    image: alarcia-dev:latest
    labels:
      caddy: app.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - nexus_net
    restart: unless-stopped

secrets:
  gh_token:
    environment: GITHUB_TOKEN

networks:
  nexus_net:
    external: true
