services:
  web:
    container_name: alarcia-dev
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - gh_token
    image: alarcia-dev:latest
    ports:
      - "8080:80"
    restart: unless-stopped

secrets:
  gh_token:
    environment: GITHUB_TOKEN
